### ISSUE TITLE
Model path not exists

### ISSUE THREAD

**Issue by Orange2223** [moothes/A2S-USOD#1]
My environment is Ubuntu18.04, python3.8, torch1.7.1 in Anaconda

As the Usage, I try to run the code. However, in base/encoder/resnet.py _resnet function, where it loads a pretrained model, the path is '/public/users/zhouhj/PretrainModel/moco_v2_800ep_pretrain.pth.tar', which doesn't exist in my environment.

Could you please offer the specific url?

**Comment by moothes** [comment]
Thanks for your attention on our work.
The pre-trained weight is Moco-v2, we have provided the project page in our README.
I copy the link here: https://github.com/facebookresearch/moco
